export const SET_DEBUGREQUEST_COUNT = 'SET_DEBUGREQUEST_COUNT'
export const SET_DEBUGREQUEST_RESPONSE = 'SET_DEBUGREQUEST_RESPONSE'
export const SET_DEBUGREQUEST_REQUESTTIME = 'SET_DEBUGREQUEST_REQUESTTIME'

export const SET_DEBUGREQUEST_SECRETKEYS = 'SET_DEBUGREQUEST_SECRETKEYS'

export const SET_DEBUGREQUEST_SECRETKEY = 'SET_DEBUGREQUEST_SECRETKEY'

// tab页数据
export const SELETE_TABDATA_INFODATAITEM = 'SELETE_TABDATA_INFODATAITEM'
export const INSERT_TABDATA_ADDTAB = 'INSERT_TABDATA_ADDTAB'
export const UPDATE_TABDATA_INFODATA = 'UPDATE_TABDATA_INFODATA'
export const DELETE_TABDATA_DELETETAB = 'DELETE_TABDATA_DELETETAB'
export const CLEAR_TABDATA_CLEARTAB = 'CLEAR_TABDATA_CLEARTAB'
export const UPDATE_TABDATA_UPDATETABSHOW = 'UPDATE_TABDATA_UPDATETABSHOW'
// 账号验证
export const DECIDE_ACCOUNT_ISVERIFY = 'DECIDE_ACCOUNT_ISVERIFY'
export const DECIDE_ACCOUNT_DECIDEACCOUNT = 'DECIDE_ACCOUNT_DECIDEACCOUNT'

// 接口数据
export const UPDATE_DROPDOWN_DROPDOWNDATA = 'UPDATE_DROPDOWN_DROPDOWNDATA'
export const UPDATE_DROPDOWN_DROPDOWNCOUNT = 'UPDATE_DROPDOWN_DROPDOWNCOUNT'
export const UPDATE_BOXCONTENT_BOXCONTENT = 'UPDATE_BOXCONTENT_BOXCONTENT'





